FROM node:16
WORKDIR /home/node/app
COPY --chown=node:node package*.json ./
RUN mkdir dist/
RUN chown -R node:node ./
USER node
RUN npm install
COPY --chown=node:node . ./
RUN npm run build
EXPOSE 3000
CMD ["node", "dist/main.js"]